### ISSUE TITLE
check_postgres support

### ISSUE THREAD

**Issue by denishpatel** [OPMDG/opm-doc#6]
Hello,

Does OPM support output of check_postgres https://bucardo.org/wiki/Check_postgres ?

**Comment by rjuju** [comment]
Hello,

Yes, as long as you use the default output.

**Comment by denishpatel** [comment]
Thanks. I will try it out. any chance you guide me on the changes I have to make to use check_potgres instead of check_nagios?

**Comment by rjuju** [comment]
You mean instead of check_pgactivity?

I can help, but there's nothing specific with check_pgactivity. If you setup a nagios server with opm, any probe that outputs perfdata (check_postgres, check_pgactivity or any other one) will be automatically handled.

So, you just need to configure services in nagios using check_postgres.

**Comment by denishpatel** [comment]
thanks a lot for quick response. I will give a try and let you know if I need help.

**Comment by rjuju** [comment]
Ok, feel free to ask if you have any issue or if we can improve documentation.

**Comment by rjuju** [comment]
Hello Denish,

Do you need other help?
